import type { AssetCategory, TaskTemplate } from "@/types";

interface AssetTypeData {
  name: string;
  category: AssetCategory;
  iconSlug: string;
  hasMeter: boolean;
  meterUnit?: string;
}

export const assetTypesData: AssetTypeData[] = [
  // 🏠 Home
  { name: "House", category: "home", iconSlug: "home", hasMeter: false },
  { name: "Apartment", category: "home", iconSlug: "building", hasMeter: false },
  { name: "Condo", category: "home", iconSlug: "building-2", hasMeter: false },
  { name: "Cabin", category: "home", iconSlug: "trees", hasMeter: false },
  { name: "Vacation Home", category: "home", iconSlug: "palmtree", hasMeter: false },

  // 🚗 Vehicle
  { name: "Car", category: "vehicle", iconSlug: "car", hasMeter: true, meterUnit: "km" },
  { name: "Truck", category: "vehicle", iconSlug: "truck", hasMeter: true, meterUnit: "km" },
  { name: "Van", category: "vehicle", iconSlug: "car", hasMeter: true, meterUnit: "km" },
  { name: "RV/Motorhome", category: "vehicle", iconSlug: "caravan", hasMeter: true, meterUnit: "km" },
  { name: "Motorcycle", category: "vehicle", iconSlug: "bike", hasMeter: true, meterUnit: "km" },
  { name: "Dirt Bike", category: "vehicle", iconSlug: "bike", hasMeter: true, meterUnit: "hours" },
  { name: "Quad", category: "vehicle", iconSlug: "square", hasMeter: true, meterUnit: "hours" },
  { name: "Side By Side", category: "vehicle", iconSlug: "square", hasMeter: true, meterUnit: "hours" },
  { name: "UTV", category: "vehicle", iconSlug: "square", hasMeter: true, meterUnit: "hours" },
  { name: "Golf Cart", category: "vehicle", iconSlug: "car", hasMeter: false },
  { name: "Snowmobile", category: "vehicle", iconSlug: "snowflake", hasMeter: true, meterUnit: "km" },

  // 🚤 Marine
  { name: "Motorboat", category: "marine", iconSlug: "ship", hasMeter: true, meterUnit: "hours" },
  { name: "Sailboat", category: "marine", iconSlug: "sailboat", hasMeter: false },
  { name: "Jet Ski", category: "marine", iconSlug: "waves", hasMeter: true, meterUnit: "hours" },

  // 🚛 Trailer
  { name: "Travel Trailer", category: "trailer", iconSlug: "caravan", hasMeter: false },
  { name: "5th Wheel", category: "trailer", iconSlug: "caravan", hasMeter: false },
  { name: "Cargo Trailer", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Utility Trailer", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Dump Trailer", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Car Hauler", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Motorcycle Trailer", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Horse Trailer", category: "trailer", iconSlug: "container", hasMeter: false },
  { name: "Boat Trailer", category: "trailer", iconSlug: "container", hasMeter: false },

  // ✈️ Aviation
  { name: "Airplane", category: "aviation", iconSlug: "plane", hasMeter: true, meterUnit: "hours" },
  { name: "Helicopter", category: "aviation", iconSlug: "plane", hasMeter: true, meterUnit: "hours" },
  { name: "Ultralight", category: "aviation", iconSlug: "plane", hasMeter: true, meterUnit: "hours" },
  { name: "Drone", category: "aviation", iconSlug: "radio", hasMeter: true, meterUnit: "hours" },
  { name: "Glider", category: "aviation", iconSlug: "plane", hasMeter: false },
  { name: "Paraglider", category: "aviation", iconSlug: "plane", hasMeter: false },

  // 🚲 Human-Powered
  { name: "Bicycle", category: "human_powered", iconSlug: "bike", hasMeter: false },
  { name: "Mountain Bike", category: "human_powered", iconSlug: "mountain", hasMeter: false },
  { name: "Road Bike", category: "human_powered", iconSlug: "bike", hasMeter: false },

  // 🌿 Lawn & Garden
  { name: "Lawn Mower", category: "lawn_garden", iconSlug: "scissors", hasMeter: true, meterUnit: "hours" },
  { name: "Lawn Tractor", category: "lawn_garden", iconSlug: "tractor", hasMeter: true, meterUnit: "hours" },
  { name: "Tractor", category: "lawn_garden", iconSlug: "tractor", hasMeter: true, meterUnit: "hours" },
  { name: "Blower", category: "lawn_garden", iconSlug: "wind", hasMeter: false },
  { name: "Chainsaw", category: "lawn_garden", iconSlug: "axe", hasMeter: false },
  { name: "Hedge Trimmer", category: "lawn_garden", iconSlug: "scissors", hasMeter: false },
  { name: "String Trimmer", category: "lawn_garden", iconSlug: "scissors", hasMeter: false },
  { name: "Lawn Edger", category: "lawn_garden", iconSlug: "scissors", hasMeter: false },
  { name: "Log Splitter", category: "lawn_garden", iconSlug: "axe", hasMeter: false },
  { name: "Pressure Washer", category: "lawn_garden", iconSlug: "droplets", hasMeter: false },
  { name: "Snow Blower", category: "lawn_garden", iconSlug: "snowflake", hasMeter: false },
  { name: "Portable Generator", category: "lawn_garden", iconSlug: "zap", hasMeter: true, meterUnit: "hours" },
  { name: "Pool", category: "lawn_garden", iconSlug: "waves", hasMeter: false },
  { name: "Hot Tub", category: "lawn_garden", iconSlug: "waves", hasMeter: false },
  { name: "Irrigation System", category: "lawn_garden", iconSlug: "droplets", hasMeter: false },
  { name: "Greenhouse", category: "lawn_garden", iconSlug: "flower-2", hasMeter: false },
  { name: "Cold Plunge", category: "lawn_garden", iconSlug: "snowflake", hasMeter: false },

  // 🔧 Shop & Tools
  { name: "Air Compressor", category: "shop_tools", iconSlug: "gauge", hasMeter: true, meterUnit: "hours" },
  { name: "Shop Vac", category: "shop_tools", iconSlug: "trash-2", hasMeter: false },
  { name: "Welder", category: "shop_tools", iconSlug: "zap", hasMeter: false },
  { name: "Vehicle Lift", category: "shop_tools", iconSlug: "arrow-up", hasMeter: false },
  { name: "Table Saw", category: "shop_tools", iconSlug: "circle", hasMeter: false },
  { name: "Drill Press", category: "shop_tools", iconSlug: "crosshair", hasMeter: false },
  { name: "Band Saw", category: "shop_tools", iconSlug: "circle", hasMeter: false },
  { name: "3D Printer", category: "shop_tools", iconSlug: "printer", hasMeter: true, meterUnit: "hours" },
  { name: "CNC", category: "shop_tools", iconSlug: "cpu", hasMeter: true, meterUnit: "hours" },
  { name: "Lathe", category: "shop_tools", iconSlug: "circle", hasMeter: false },
  { name: "Bench Grinder", category: "shop_tools", iconSlug: "circle", hasMeter: false },
  { name: "Jointer", category: "shop_tools", iconSlug: "minus", hasMeter: false },
  { name: "Planer", category: "shop_tools", iconSlug: "minus", hasMeter: false },
  { name: "Router Table", category: "shop_tools", iconSlug: "grid-3x3", hasMeter: false },

  // 🏗️ Heavy Equipment
  { name: "Boom Lift", category: "heavy_equipment", iconSlug: "arrow-up", hasMeter: true, meterUnit: "hours" },
  { name: "Dump Truck", category: "heavy_equipment", iconSlug: "truck", hasMeter: true, meterUnit: "km" },
  { name: "Backhoe", category: "heavy_equipment", iconSlug: "shovel", hasMeter: true, meterUnit: "hours" },
  { name: "Excavator", category: "heavy_equipment", iconSlug: "shovel", hasMeter: true, meterUnit: "hours" },
  { name: "Crane", category: "heavy_equipment", iconSlug: "arrow-up", hasMeter: true, meterUnit: "hours" },
  { name: "Forklift", category: "heavy_equipment", iconSlug: "move-vertical", hasMeter: true, meterUnit: "hours" },
  { name: "Skid Steer", category: "heavy_equipment", iconSlug: "square", hasMeter: true, meterUnit: "hours" },
  { name: "Telehandler", category: "heavy_equipment", iconSlug: "arrow-up-right", hasMeter: true, meterUnit: "hours" },

  // 🎣 Gear & Equipment
  { name: "Fishing Reel", category: "gear_equipment", iconSlug: "fish", hasMeter: false },
  { name: "Hunting Rifle", category: "gear_equipment", iconSlug: "crosshair", hasMeter: false },
  { name: "Shotgun", category: "gear_equipment", iconSlug: "crosshair", hasMeter: false },
  { name: "Archery Equipment", category: "gear_equipment", iconSlug: "target", hasMeter: false },
  { name: "Ice Skates", category: "gear_equipment", iconSlug: "snowflake", hasMeter: false },
  { name: "Downrigger", category: "gear_equipment", iconSlug: "anchor", hasMeter: false },
  { name: "Gun Safe", category: "gear_equipment", iconSlug: "lock", hasMeter: false },
];

// Task templates by asset type
export const taskTemplates: Record<string, TaskTemplate[]> = {
  House: [
    { title: "Smoke Detector Battery Change", taskType: "time_based", intervalValue: 12, intervalUnit: "month", category: "safety" },
    { title: "CO Detector Test", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "CO Detector Expiry", taskType: "time_based", intervalValue: 10, intervalUnit: "year", category: "safety" },
    { title: "Fire Extinguisher Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Dry Chem Extinguisher Service", taskType: "time_based", intervalValue: 6, intervalUnit: "year", category: "safety" },
    { title: "Dryer Vent Clean", taskType: "time_based", intervalValue: 12, intervalUnit: "month", category: "safety" },
    { title: "Chimney Clean", taskType: "time_based", intervalValue: 12, intervalUnit: "month", category: "safety", condition: "fireplace" },
    { title: "Check First Aid Kit", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Clean Fridge Coils", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Clean Gutters", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Change Furnace Filter", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Replace Hot Water Heater", taskType: "time_based", intervalValue: 10, intervalUnit: "year", category: "preventative" },
    { title: "Put Up Christmas Lights", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "festive" },
    { title: "Take Down Christmas Lights", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "festive" },
    { title: "Change UV Light", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative", condition: "well_uv" },
    { title: "Add Salt", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative", condition: "water_softener" },
    { title: "Pump Out Septic", taskType: "time_based", intervalValue: 3, intervalUnit: "year", category: "preventative", condition: "septic" },
  ],
  Apartment: [
    { title: "Smoke Detector Test", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "CO Detector Test", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check First Aid Kit", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Clean Range Hood Filter", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Clean Fridge Coils", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  Condo: [
    { title: "Smoke Detector Test", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "CO Detector Test", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check First Aid Kit", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Clean Range Hood Filter", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Clean Fridge Coils", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  Car: [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 5000, cycleUnit: "km", category: "preventative" },
    { title: "Tire Pressure Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Wear Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Wiper Replacement", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Check Brakes", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Check First Aid Kit", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Battery Condition", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Inspect Belts & Hoses", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Rotate Tires", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Cabin Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Engine Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Install Winter Tires", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Install Summer Tires", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Coolant", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Washer Fluid", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Car Seat Expiry", taskType: "time_based", intervalValue: 8, intervalUnit: "year", category: "safety", condition: "car_seat" },
    { title: "DEF Fluid", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative", condition: "diesel" },
  ],
  Truck: [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 5000, cycleUnit: "km", category: "preventative" },
    { title: "Tire Pressure Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Wear Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Wiper Replacement", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Check Brakes", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Check First Aid Kit", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Battery Condition", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Inspect Belts & Hoses", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Rotate Tires", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Cabin Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Engine Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Install Winter Tires", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Install Summer Tires", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Coolant", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Washer Fluid", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "DEF Fluid", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative", condition: "diesel" },
  ],
  Van: [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 5000, cycleUnit: "km", category: "preventative" },
    { title: "Tire Pressure Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Wear Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Wiper Replacement", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Check Brakes", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Battery Condition", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Inspect Belts & Hoses", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Rotate Tires", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Cabin Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Engine Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Coolant", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Washer Fluid", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
  ],
  Motorcycle: [
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Brake Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test Horn", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Clutch & Throttle Freeplay", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Helmet Expiry", taskType: "time_based", intervalValue: 5, intervalUnit: "year", category: "safety" },
    { title: "Check Oil", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Chain Clean", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Chain Adjustment", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Lubricate Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Brake Fluid Change", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "preventative" },
    { title: "Clean Air Intake", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Check Suspension for Leaks", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Battery Test", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Spark Plugs", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Coolant Change", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "preventative" },
    { title: "Winterize", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  Motorboat: [
    { title: "Test Bilge Pump", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test Nav Lights", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test VHF Radio", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test EPIRB/SART", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Lifejackets", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Flares", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Replace Flares", taskType: "time_based", intervalValue: 4, intervalUnit: "year", category: "safety" },
    { title: "Inspect Fuel Lines", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Test Blower", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Oil Level", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Anodes", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Lubricate Steering", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Inspect Battery & Connections", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Change Impeller", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Change Gear Oil", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 100, cycleUnit: "hours", category: "preventative" },
    { title: "Check Bottom Paint", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Through Hulls", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Replace Fuel Hoses", taskType: "time_based", intervalValue: 5, intervalUnit: "year", category: "preventative" },
    { title: "Check Hatch/Door Seals", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Change Thermostat", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "preventative" },
  ],
  Sailboat: [
    { title: "Test Bilge Pump", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test Nav Lights", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test VHF Radio", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Lifejackets", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Flares", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Replace Flares", taskType: "time_based", intervalValue: 4, intervalUnit: "year", category: "safety" },
    { title: "Inspect Standing Rigging", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Inspect Running Rigging", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "safety" },
    { title: "Check Anodes", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Check Bottom Paint", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Through Hulls", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Check Hatch/Door Seals", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Inspect Sails", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "Jet Ski": [
    { title: "Test Bilge Pump", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Lifejackets", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Oil Level", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Change Impeller", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 50, cycleUnit: "hours", category: "preventative" },
    { title: "Inspect Battery", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Winterize", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Travel Trailer": [
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Safety Chain Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test Brake-Away", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Grease Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Repack Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Frame & Suspension", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check for Propane Leaks", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test CO/Smoke Detector", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test GFCI", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Drain/Flush Fresh Water System", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "5th Wheel": [
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Safety Chain Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Grease Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Repack Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Frame & Suspension", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check for Propane Leaks", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test CO/Smoke Detector", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Test GFCI", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Drain/Flush Fresh Water System", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "Cargo Trailer": [
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Safety Chain Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Grease Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Repack Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Frame & Suspension", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Utility Trailer": [
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Safety Chain Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Grease Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Repack Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Inspect Frame & Suspension", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Boat Trailer": [
    { title: "Tire Wear", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Lug Nut Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Light Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Safety Chain Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Grease Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Repack Bearings", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Bunks/Rollers", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Check Winch Strap", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "safety" },
    { title: "Inspect Frame & Suspension", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Mountain Bike": [
    { title: "Check Brakes", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Tire Sealant", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Bolts", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Lubricate Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Fork Service", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Shock Service", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Dropper Service", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  Bicycle: [
    { title: "Check Brakes", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Lubricate Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Bolts", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
  ],
  "Road Bike": [
    { title: "Check Brakes", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Tire Pressure", taskType: "time_based", intervalValue: 1, intervalUnit: "week", category: "safety" },
    { title: "Check Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Lubricate Chain", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Bolts", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Bar Tape Replacement", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  Airplane: [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 50, cycleUnit: "hours", category: "preventative" },
    { title: "ELT Battery Expiry", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "safety" },
    { title: "AED Battery Expiry", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "safety" },
    { title: "AED Pads Expiry", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "safety" },
    { title: "Annual Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "regulatory" },
    { title: "Transponder Check", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "regulatory" },
    { title: "Pitot-Static Check", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "regulatory" },
  ],
  Helicopter: [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 25, cycleUnit: "hours", category: "preventative" },
    { title: "ELT Battery Expiry", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "safety" },
    { title: "Annual Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "regulatory" },
    { title: "Transponder Check", taskType: "time_based", intervalValue: 2, intervalUnit: "year", category: "regulatory" },
  ],
  Drone: [
    { title: "Prop Inspection", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Battery Health Check", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Firmware Update", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Motor Inspection", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "Air Compressor": [
    { title: "Drain Tank", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Hoses", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "safety" },
    { title: "Change Oil", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Replace Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Shop Vac": [
    { title: "Clean Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "safety" },
    { title: "Check Hose", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Replace Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Table Saw": [
    { title: "Oil & Wax Cast Iron Table", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Check Blade Alignment", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Blade Sharpness", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "safety" },
  ],
  Lathe: [
    { title: "Lubricate Ways & Lead Screws", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Alignment", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "3D Printer": [
    { title: "Clean Bed", taskType: "time_based", intervalValue: 1, intervalUnit: "week", category: "preventative" },
    { title: "Lubricate Rails", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Check Belt Tension", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Replace Nozzle", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  "Lawn Mower": [
    { title: "Oil Change", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Sharpen Blade", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Replace Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Replace Spark Plug", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Winterize", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Lawn Tractor": [
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 50, cycleUnit: "hours", category: "preventative" },
    { title: "Sharpen Blades", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Replace Air Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Belt", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
    { title: "Grease Fittings", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
    { title: "Winterize", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Irrigation System": [
    { title: "Test Irrigation System", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Blow Out Irrigation System", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Check Sprinkler Heads", taskType: "time_based", intervalValue: 6, intervalUnit: "month", category: "preventative" },
  ],
  Pool: [
    { title: "Test Water Chemistry", taskType: "time_based", intervalValue: 1, intervalUnit: "week", category: "safety" },
    { title: "Clean Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Winterize Pool", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
    { title: "Open Pool", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
  "Hot Tub": [
    { title: "Test Water Chemistry", taskType: "time_based", intervalValue: 1, intervalUnit: "week", category: "safety" },
    { title: "Clean Filter", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Drain and Refill", taskType: "time_based", intervalValue: 3, intervalUnit: "month", category: "preventative" },
  ],
  "Portable Generator": [
    { title: "Run Generator", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Oil Change", taskType: "cycle_based", cycleInterval: 50, cycleUnit: "hours", category: "preventative" },
    { title: "Check Fuel", taskType: "time_based", intervalValue: 1, intervalUnit: "month", category: "preventative" },
    { title: "Replace Spark Plug", taskType: "time_based", intervalValue: 1, intervalUnit: "year", category: "preventative" },
  ],
};

// Categories for the UI
export const assetCategories: { id: AssetCategory; name: string; icon: string; emoji: string }[] = [
  { id: "home", name: "Home", icon: "home", emoji: "🏠" },
  { id: "vehicle", name: "Vehicle", icon: "car", emoji: "🚗" },
  { id: "marine", name: "Marine", icon: "ship", emoji: "🚤" },
  { id: "trailer", name: "Trailer", icon: "caravan", emoji: "🚛" },
  { id: "aviation", name: "Aviation", icon: "plane", emoji: "✈️" },
  { id: "human_powered", name: "Human-Powered", icon: "bike", emoji: "🚲" },
  { id: "lawn_garden", name: "Lawn & Garden", icon: "flower-2", emoji: "🌿" },
  { id: "shop_tools", name: "Shop & Tools", icon: "wrench", emoji: "🔧" },
  { id: "heavy_equipment", name: "Heavy Equipment", icon: "hard-hat", emoji: "🏗️" },
  { id: "gear_equipment", name: "Gear & Equipment", icon: "backpack", emoji: "🎣" },
];
